version: "3.9"

services:
  db:
    image: postgres:14
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:5635:5432"
    volumes:
      - compress_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: ghcr.io/danishkkhan13/manageleadcrmbackend-prod:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:8015:8015"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./uploads:/usr/src/app/uploads
      - ./config:/usr/src/app/config

volumes:
  compress_pgdata: